### ISSUE TITLE
UTF-8 bugs

### ISSUE THREAD

**Issue by Sigmw** [rajasegar/alacritty-themes#112]
### To Reproduce

1. Installation

- [ X] I run it via npx alacritty-themes
- [ X] I installed it via npm i -g alacritty-themes (global installation)

2. Run alacritty-themes

- [ X] Did you add params? yes, I type "alacritty-themes Ayu-Dark"
- [ X] Did you add params? no, I just tipe "alacritty-themes" then click up/down keys

3. See error

### Operative System:

- [ ] Windows
- [ ] Ubuntu
- [ ] Pop Os
- [X ] Arch
- [ ] Other, which one?

### Add your alacritty.yml content
```yml
# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: alacritty
  LANG: "en_US.UTF-8"
  LC_CTYPE: en_US.UTF-8
  #window:
  # Window dimensions (changes require restart)
  #
  # Specified in number of columns/lines, not pixels.
  # If both are `0`, this setting is ignored.
  #dimensions:
  #  columns: 0
  #  lines: 0
  # Window position (changes require restart)
  #
  # Specified in number of pixels.
  # If the position is not set, the window manager will handle the placement.
  #position:
  #  x: 0
  #  y: 0
  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  #padding:
  #  x: 0
  #  y: 0
  # Spread additional padding evenly around the terminal content.
  #dynamic_padding: false
  # Window decorations
  #
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  #
  # Values for `decorations` (macOS only):
  #     - transparent: Title bar, transparent background and title bar buttons
  #     - buttonless: Title bar, transparent background, but no title bar buttons
  #decorations: full
  # Startup Mode (changes require restart)
  #
  # Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  #
  # Values for `startup_mode` (macOS only):
  #   - SimpleFullscreen
  #startup_mode: Windowed
  # Window title
  #title: Alacritty
  # Window class (Linux/BSD only):
  #class:
  # Application instance name
  #instance: Alacritty
  # General application class
  #general: Alacritty
  # GTK theme variant (Linux/BSD only)
  #
  # Override the variant of the GTK theme. Commonly supported values are `dark` and `light`.
  # Set this to `None` to use the default theme variant.
  #gtk_theme_variant: None
  #scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  #history: 10000
  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  #multiplier: 3

# Font configuration
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
    family: "monospace"

    # The `style` can be specified to pick a specific face.
    style: Regular
    # Bold font face
    #bold:
    # Font family
    #
    # If the bold family is not specified, it will fall back to the
    # value specified for the normal font.
    #family: monospace
    # The `style` can be specified to pick a specific face.
    #style: Bold
    # Italic font face
    #italic:
    # Font family
    #
    # If the italic family is not specified, it will fall back to the
    # value specified for the normal font.
    #family: monospace
    # The `style` can be specified to pick a specific face.
    #style: Italic
    # Bold italic font face
    #bold_italic:
    # Font family
    #
    # If the bold italic family is not specified, it will fall back to the
    # value specified for the normal font.
    #family: monospace
    # The `style` can be specified to pick a specific face.
    #style: Bold Italic

  # Point size
  size: 11.0

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  #offset:
  #  x: 0
  #  y: 0
  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upwards.
  #glyph_offset:
  #  x: 0
  #  y: 0
  # Thin stroke font rendering (macOS only)
  #
  # Thin strokes are suitable for retina displays, but for non-retina screens
  # it is recommended to set `use_thin_strokes` to `false`
  #
  # macOS >= 10.14.x:
  #
  # If the font quality on non-retina display looks bad then set
  # `use_thin_strokes` to `true` and enable font smoothing by running the
  # following command:
  #   `defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO`
  #
  # This is a global setting and will require a log out or restart to take
  # effect.
  use_thin_strokes: true

# If `true`, bold text is drawn using the bright color variants.
#draw_bold_text_with_bright_colors: false
# Colors (Tomorrow Night Bright)
colors:
  # Default colors
  primary:
    background: '#002b36' # base03
    foreground: '#839496' # base0

  # Cursor colors
  cursor:
    text: '#002b36' # base03
    cursor: '#839496' # base0

  # Normal colors
  normal:
    black: '#073642' # base02
    red: '#dc322f' # red
    green: '#859900' # green
    yellow: '#b58900' # yellow
    blue: '#268bd2' # blue
    magenta: '#d33682' # magenta
    cyan: '#2aa198' # cyan
    white: '#eee8d5' # base2

  # Bright colors
  bright:
    black: '#002b36' # base03
    red: '#cb4b16' # orange
    green: '#586e75' # base01
    yellow: '#657b83' # base00
    blue: '#839496' # base0
    magenta: '#6c71c4' # violet
    cyan: '#93a1a1' # base1
    white: '#fdf6e3' # base3
theme: Solarized-Dark
```

### Screenshots
![image](https://user-images.githubusercontent.com/89428643/157353781-819b9ae2-ed66-4c41-9547-7b105702eca7.png)
Add screenshots to help explain your problem.

Yup, UTF-8 bug with accentts when i set theme

**Comment by JuanVqz** [comment]
Hi @Sigmw thank you for opening this issue.

do you still running the issue?

To me it seems like it's not related to `alacritty-themes`, the purpose of `alacritty-themes` is change the theme color easily.

I'm seen that you have the following lines, have you tried comment them and reopen the terminal? 

```yml
env:
  LANG: "en_US.UTF-8"
  LC_CTYPE: en_US.UTF-8
```
