### ISSUE TITLE
Too many backups

### ISSUE THREAD

**Issue by alexmailo** [rajasegar/alacritty-themes#165]
### Describe the bug

Looks like every time it runs, it creates a backup file for some reason. Was wondering if that is necessary or is it a bug?

### To Reproduce

1. Installation

- [ ] I run it via npx alacritty-themes
- [x] I installed it via npm i -g alacritty-themes (global installation)

2. Run alacritty-themes

- [ ] Did you add params? yes, I type "alacritty-themes Ayu-Dark"
- [x] Did you add params? no, I just type "alacritty-themes" then click up/down keys

3. See error

### Expected behavior

Just run normally without creating multiple backup files

### Operating System:

- [ ] Windows
- [ ] Ubuntu
- [ ] Pop Os
- [x] Arch
- [ ] Other, which one?

### Add your alacritty.yml content

```yml
font:
  size: 14
  normal:
    family: Fira Code Medium
    # in terminal of angela
    # family: Monaco
    # family: Cousine
    style: Regular
  offset:
    x: 0
    y: 5
shell:
  program: /bin/zsh
traw_bold_text_with_bright_colors: false
window:
  # requires compositor running
  opacity: 1
  padding:
    x: 10
    y: 10
cursor:
  style:
    shape: Beam
    blinking: On
import:
  - ~/.config/alacritty/themes/challenger-deep.yml
colors:
  name: 3024 (dark)
  author: Chris Kempson
  primary:
    background: "#090300"
    foreground: "#a5a2a2"
  cursor:
    text: "#090300"
    cursor: "#a5a2a2"
  normal:
    black: "#090300"
    red: "#db2d20"
    green: "#01a252"
    yellow: "#fded02"
    blue: "#01a0e4"
    magenta: "#a16a94"
    cyan: "#b5e4f4"
    white: "#a5a2a2"
  bright:
    black: "#5c5855"
    red: "#db2d20"
    green: "#01a252"
    yellow: "#fded02"
    blue: "#01a0e4"
    magenta: "#a16a94"
    cyan: "#b5e4f4"
    white: "#f7f7f7"
theme: 3024.dark

```

### Screenshots
![alacritty-themes](https://user-images.githubusercontent.com/59002720/179364580-f9f70dcc-948a-4698-be75-8b97d632a017.png)
