### ISSUE TITLE
Direct theme application not working

### ISSUE THREAD

**Issue by tigerjack** [rajasegar/alacritty-themes#183]
### Describe the bug

Cannot apply a theme directly; the menu list is always shown. 

### To Reproduce

1. Installation

- [ ] I run it via npx alacritty-themes
- [ ] I installed it via npm i -g alacritty-themes (global installation)
- [x] I installed it via AUR 

2. Run alacritty-themes

- [x] Did you add params? yes, I type "alacritty-themes Ayu-Dark"
- [ ] Did you add params? no, I just type "alacritty-themes" then click up/down keys

3. See error
![image](https://user-images.githubusercontent.com/8199216/188264782-d6272a54-6ef9-4cb4-8ae1-4f36addb3dd9.png)

### Expected behavior

The theme should be directly applied.

### Operating System:

- [ ] Windows
- [ ] Ubuntu
- [ ] Pop Os
- [x] Arch
- [ ] Other, which one?

### Add your alacritty.yml content

```yml

env:
  TERM: alacritty
  LANG: "en_US.UTF-8"
  LC_CTYPE: en_US.UTF-8

font:
  normal:
    family: "monospace"

    style: Regular

  size: 11.0

colors:
  name: 3024 (dark)
  author: Chris Kempson
  primary:
    background: "#090300"
    foreground: "#a5a2a2"
  cursor:
    text: "#090300"
    cursor: "#a5a2a2"
  normal:
    black: "#090300"
    red: "#db2d20"
    green: "#01a252"
    yellow: "#fded02"
    blue: "#01a0e4"
    magenta: "#a16a94"
    cyan: "#b5e4f4"
    white: "#a5a2a2"
  bright:
    black: "#5c5855"
    red: "#db2d20"
    green: "#01a252"
    yellow: "#fded02"
    blue: "#01a0e4"
    magenta: "#a16a94"
    cyan: "#b5e4f4"
    white: "#f7f7f7"
theme: 3024.dark
```
