### ISSUE TITLE
Alacritty 0.14.0 -  import has been deprecated; use general.import instead 

### ISSUE THREAD

**Issue by killeik** [rajasegar/alacritty-themes#267]
### Describe the bug

After alacritty update to 0.14.0 import=[] is deprecated, alacritty-themes need to set [general] and then import=[] in config file

### To Reproduce

1. Installation

- I run it via npx alacritty-themes

2. Run alacritty-themes

- I just type "npx alacritty-themes" then click up/down keys, any theme and enter

3. See error
```
[WARN] Config warning: import has been deprecated; use general.import instead 
Use 'alacritty migrate' to automatically resolve it 
```

### Expected behavior
alacritty-themes successfully adds to the config file:
```toml
import = [
  "/usr/lib/node_modules/alacritty-themes/themes/3024.dark.toml"
]
```

But it should add:
```toml
[general]
import = [
  "/usr/lib/node_modules/alacritty-themes/themes/3024.dark.toml"
]

```
### Operating System:

- Arch

### Add your alacritty.yml content
it's toml btw:

```toml
import = [
  "/usr/lib/node_modules/alacritty-themes/themes/Gruvbox-Light.toml"
]

[window]
decorations = "none"
opacity = 0.9
dynamic_padding = true

[env]
TERM = "xterm-256color"

[font]
size = 13
```

### Screenshots
![image](https://github.com/user-attachments/assets/13d3bfdd-043b-40f9-b10b-ee1f7a762b26)
