### ISSUE TITLE
Themes still use deprecated background_opacity field.

### ISSUE THREAD

**Issue by michaelmoreno** [rajasegar/alacritty-themes#98]
### Describe the bug

Any terminal instances I open have a big yellow warning message at the bottom saying
```[WARN] See log at /tmp/Alacritty-43629.log ($ALACRITTY):
Config warning: background_opacity is deprecated; use window.opacity instead```

I could go to my `~/.config/alacritty/alacritty.yml` and manually change the field, but it will revert everytime I run `alacritty-themes` to switch to another theme.
### To Reproduce

1. Installation

- I run it via `alacritty-themes`
- I installed it via `yay -s alacritty-themes`

2. Run `alacritty-themes`

### Operative System:
Arch, Linux 5.15.19-1-lts

### An example of a theme `.yml` file that `alacritty-themes` writes to `~/config/alacritty/alacritty.yml`
```yml
colors:
  name: Atelierheath (dark)
  author: Chris Kempson
  primary:
    background: "#1b181b"
    foreground: "#ab9bab"
  cursor:
    text: "#1b181b"
    cursor: "#ab9bab"
  normal:
    black: "#1b181b"
    red: "#ca402b"
    green: "#379a37"
    yellow: "#bb8a35"
    blue: "#516aec"
    magenta: "#7b59c0"
    cyan: "#159393"
    white: "#ab9bab"
  bright:
    black: "#776977"
    red: "#ca402b"
    green: "#379a37"
    yellow: "#bb8a35"
    blue: "#516aec"
    magenta: "#7b59c0"
    cyan: "#159393"
    white: "#f7f3f7"

background_opacity: 0.8
theme: Atelierheath.dark
me: Default.light
```

### Screenshots

Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/72640530/153483074-0e3d2245-9125-4680-9acf-94eb4d665652.png)

**Comment by JuanVqz** [comment]
Hi @michaelmoreno, Thank you for opening this issue, you just need to change from `background_opacity` to the `opacity` attribute. 

```yml
colors:
  name: Atelierheath (dark)
  author: Chris Kempson
  primary:
    background: "#1b181b"
    foreground: "#ab9bab"
  cursor:
    text: "#1b181b"
    cursor: "#ab9bab"
  normal:
    black: "#1b181b"
    red: "#ca402b"
    green: "#379a37"
    yellow: "#bb8a35"
    blue: "#516aec"
    magenta: "#7b59c0"
    cyan: "#159393"
    white: "#ab9bab"
  bright:
    black: "#776977"
    red: "#ca402b"
    green: "#379a37"
    yellow: "#bb8a35"
    blue: "#516aec"
    magenta: "#7b59c0"
    cyan: "#159393"
    white: "#f7f3f7"

opacity: 0.8
theme: Atelierheath.dark
me: Default.light
```
Update alacritty template https://github.com/rajasegar/alacritty-themes/pull/99
